### ISSUE TITLE
where should the dataset i put?

### ISSUE THREAD

**Issue by rainbowjack** [KinWaiCheuk/Jointist#1]
i downloaded the slakh but i dont know where should i put it

**Comment by KinWaiCheuk** [comment]
Hi, you can put it anywhere and then specify the dataset path inside the config. For example, if you want to train the transcription model:
https://github.com/KinWaiCheuk/Jointist/blob/1846975ec904c8b23ea653b9b7881f343574e7a6/End2End/config/datamodule/slakh.yaml#L1

I think there are some config files that I still haven't updated yet. I will try to update the code when I have time later.

**Comment by rainbowjack** [comment]
thanks，i will try later
By the way，Is this program Work fine on Windows？

**Comment by KinWaiCheuk** [comment]
Since this program depends on pytorch and python, I would assume that as long as you have both of them installed properly on Windows, it will work.
But I haven't test it on Windows, so I am not 100% sure.
